-- File generated by the BNF Converter (bnfc 2.9.4).

-- | The abstract syntax of language Erl.

module Erl.Abs where

import qualified Prelude as C (Eq, Ord, Show, Read)

data Stmt = Stmt Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Expr = SExprOne | SExprNone
  deriving (C.Eq, C.Ord, C.Show, C.Read)

