-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Obs.

module Obs.Abs where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Name = Mname ObsString
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Args = ArgsOne ObsString | ArgsCons ObsString Args
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LMsg = LmsgOne ObsString | LmsgCons ObsString LMsg
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Taskname = TaskName ObsString
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Varname = VarName ObsString
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Varval = VarVal ObsString
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Typename = TypeName ObsString
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data State = State ObsString
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Varindex = VarIndex Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Obs
    = ObsName Integer Name
    | ObsLog Integer LMsg
    | ObsInit Integer
    | ObsTask Integer Taskname
    | ObsSignal Integer Integer
    | ObsDef Integer Varname Varval
    | ObsDeclVal Integer Typename Varname Varval
    | ObsDecl Integer Typename Varname
    | ObsDeclArr Integer Typename Varname Varval
    | ObsCall Integer Args
    | ObsState Integer Integer State
    | ObsStruct Integer Varname
    | ObsSeq Integer Varname Scalar
    | ObsPtr Integer Varname Varval
    | ObsScalar Integer Varname Varval
    | ObsScalarIndex Integer Varname Varindex Varval
    | ObsEnd Integer Varname
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Scalar
    = ObsScalarCons Integer Varval Scalar | ObsScalarNone End
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data End = ObsEndSeq Integer Varname
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype ObsString = ObsString String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

