-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.4).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module Obs.Par
  ( happyError
  , myLexer
  , pListObs
  , pObs
  , pScalar
  , pEnd
  , pArgs
  , pTaskname
  , pVarname
  , pVarval
  , pTypename
  , pStateObs
  , pVarindex
  , pThreadId
  , pSizeDcl
  ) where

import Prelude

import qualified Obs.Abs
import Obs.Lex

}

%name pListObs ListObs
%name pObs Obs
%name pScalar Scalar
%name pEnd End
%name pArgs Args
%name pTaskname Taskname
%name pVarname Varname
%name pVarval Varval
%name pTypename Typename
%name pStateObs StateObs
%name pVarindex Varindex
%name pThreadId ThreadId
%name pSizeDcl SizeDcl
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '@@@'      { PT _ (TS _ 1)        }
  'CALL'     { PT _ (TS _ 2)        }
  'DCLARRAY' { PT _ (TS _ 3)        }
  'DECL'     { PT _ (TS _ 4)        }
  'DEF'      { PT _ (TS _ 5)        }
  'END'      { PT _ (TS _ 6)        }
  'INIT'     { PT _ (TS _ 7)        }
  'NAME'     { PT _ (TS _ 8)        }
  'NULL'     { PT _ (TS _ 9)        }
  'PTR'      { PT _ (TS _ 10)       }
  'SCALAR'   { PT _ (TS _ 11)       }
  'SEQ'      { PT _ (TS _ 12)       }
  'SIGNAL'   { PT _ (TS _ 13)       }
  'STATE'    { PT _ (TS _ 14)       }
  'STRUCT'   { PT _ (TS _ 15)       }
  'TASK'     { PT _ (TS _ 16)       }
  '_'        { PT _ (TS _ 17)       }
  L_doubl    { PT _ (TD $$)         }
  L_integ    { PT _ (TI $$)         }
  L_ObsIdent { PT _ (T_ObsIdent $$) }
  L_ObsStr   { PT _ (T_ObsStr $$)   }

%%

Double  :: { Double }
Double   : L_doubl  { (read $1) :: Double }

Integer :: { Integer }
Integer  : L_integ  { (read $1) :: Integer }

ObsIdent :: { Obs.Abs.ObsIdent }
ObsIdent  : L_ObsIdent { Obs.Abs.ObsIdent $1 }

ObsStr :: { Obs.Abs.ObsStr }
ObsStr  : L_ObsStr { Obs.Abs.ObsStr $1 }

ListObs :: { [Obs.Abs.Obs] }
ListObs : '@@@' Obs ListObs { (:) $2 $3 } | '@@@' Obs { (:[]) $2 }

Obs :: { Obs.Abs.Obs }
Obs
  : ThreadId 'NAME' ObsIdent { Obs.Abs.ObsName $1 $3 }
  | ThreadId 'INIT' { Obs.Abs.ObsInit $1 }
  | ThreadId 'TASK' Taskname { Obs.Abs.ObsTask $1 $3 }
  | ThreadId 'SIGNAL' Integer { Obs.Abs.ObsSignal $1 $3 }
  | ThreadId 'DEF' Varname Varval { Obs.Abs.ObsDef $1 $3 $4 }
  | ThreadId 'DECL' Typename Varname { Obs.Abs.ObsDecl $1 $3 $4 }
  | ThreadId 'DECL' Typename Varname Varval { Obs.Abs.ObsDeclVal $1 $3 $4 $5 }
  | ThreadId 'DCLARRAY' Typename Varname SizeDcl { Obs.Abs.ObsDeclArr $1 $3 $4 $5 }
  | ThreadId 'CALL' ObsIdent Args { Obs.Abs.ObsCall $1 $3 $4 }
  | ThreadId 'STATE' Integer StateObs { Obs.Abs.ObsState $1 $3 $4 }
  | ThreadId 'STRUCT' Varname { Obs.Abs.ObsStruct $1 $3 }
  | ThreadId 'SEQ' Varname Scalar { Obs.Abs.ObsSeq $1 $3 $4 }
  | ThreadId 'PTR' Varname Varval { Obs.Abs.ObsPtr $1 $3 $4 }
  | ThreadId 'SCALAR' Varname Varval { Obs.Abs.ObsScalar $1 $3 $4 }
  | ThreadId 'SCALAR' Varname Varindex Varval { Obs.Abs.ObsScalarIndex $1 $3 $4 $5 }
  | ThreadId 'END' Varname { Obs.Abs.ObsEnd $1 $3 }

Scalar :: { Obs.Abs.Scalar }
Scalar
  : End { Obs.Abs.ObsScalarNone $1 }
  | '@@@' ThreadId 'SCALAR' '_' Varval Scalar { Obs.Abs.ObsScalarCons $2 $5 $6 }

End :: { Obs.Abs.End }
End : '@@@' ThreadId 'END' Varname { Obs.Abs.ObsEndSeq $2 $4 }

Args :: { Obs.Abs.Args }
Args
  : ObsStr Args { Obs.Abs.ArgsConsString $1 $2 }
  | Integer Args { Obs.Abs.ArgsConsInteger $1 $2 }
  | Double Args { Obs.Abs.ArgsConsDouble $1 $2 }
  | {- empty -} { Obs.Abs.ArgsOne }

Taskname :: { Obs.Abs.Taskname }
Taskname : ObsIdent { Obs.Abs.TaskName $1 }

Varname :: { Obs.Abs.Varname }
Varname : ObsIdent { Obs.Abs.VarName $1 }

Varval :: { Obs.Abs.Varval }
Varval
  : Integer { Obs.Abs.VarValInt $1 }
  | Double { Obs.Abs.VarValDouble $1 }
  | 'NULL' { Obs.Abs.VarValNull }
  | ObsStr { Obs.Abs.VarValStr $1 }

Typename :: { Obs.Abs.Typename }
Typename : ObsIdent { Obs.Abs.TypeName $1 }

StateObs :: { Obs.Abs.StateObs }
StateObs : ObsIdent { Obs.Abs.StateObs $1 }

Varindex :: { Obs.Abs.Varindex }
Varindex : Integer { Obs.Abs.VarIndex $1 }

ThreadId :: { Obs.Abs.ThreadId }
ThreadId : Integer { Obs.Abs.ThreadId $1 }

SizeDcl :: { Obs.Abs.SizeDcl }
SizeDcl
  : Varval { Obs.Abs.SizeDclVar $1 }
  | ObsIdent { Obs.Abs.SizeDclDef $1 }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: String -> [Token]
myLexer = tokens

}

