-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Obs.

module Obs.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Obs.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Obs.Abs.ObsIdent where
  prt _ (Obs.Abs.ObsIdent i) = doc $ showString i
instance Print [Obs.Abs.Obs] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, doc (showString "\n"), prt 0 xs]

instance Print Obs.Abs.Args where
  prt i = \case
    Obs.Abs.ArgsOne -> prPrec i 0 (concatD [])
    Obs.Abs.ArgsConsInteger n args -> prPrec i 0 (concatD [prt 0 n, prt 0 args])
    Obs.Abs.ArgsConsDouble d args -> prPrec i 0 (concatD [prt 0 d, prt 0 args])
    Obs.Abs.ArgsConsString str args -> prPrec i 0 (concatD [printString str, prt 0 args])

instance Print Obs.Abs.LMsg where
  prt i = \case
    Obs.Abs.LmsgOne -> prPrec i 0 (concatD [])
    Obs.Abs.LmsgConsString str lmsg -> prPrec i 0 (concatD [printString str, prt 0 lmsg])
    Obs.Abs.LmsgConsInt n lmsg -> prPrec i 0 (concatD [prt 0 n, prt 0 lmsg])
    Obs.Abs.LmsgConsDouble d lmsg -> prPrec i 0 (concatD [prt 0 d, prt 0 lmsg])

instance Print Obs.Abs.Taskname where
  prt i = \case
    Obs.Abs.TaskName obsident -> prPrec i 0 (concatD [prt 0 obsident])

instance Print Obs.Abs.Varname where
  prt i = \case
    Obs.Abs.VarName obsident -> prPrec i 0 (concatD [prt 0 obsident])

instance Print Obs.Abs.Varval where
  prt i = \case
    Obs.Abs.VarValInt n -> prPrec i 0 (concatD [prt 0 n])
    Obs.Abs.VarValDouble d -> prPrec i 0 (concatD [prt 0 d])
    Obs.Abs.VarValNull -> prPrec i 0 (concatD [doc (showString "NULL")])

instance Print Obs.Abs.Typename where
  prt i = \case
    Obs.Abs.TypeName obsident -> prPrec i 0 (concatD [prt 0 obsident])

instance Print Obs.Abs.State where
  prt i = \case
    Obs.Abs.State obsident -> prPrec i 0 (concatD [prt 0 obsident])

instance Print Obs.Abs.Varindex where
  prt i = \case
    Obs.Abs.VarIndex n -> prPrec i 0 (concatD [prt 0 n])

instance Print Obs.Abs.ThreadId where
  prt i = \case
    Obs.Abs.ThreadId n -> prPrec i 0 (concatD [prt 0 n])

instance Print Obs.Abs.SizeDcl where
  prt i = \case
    Obs.Abs.SizeDclVar varval -> prPrec i 0 (concatD [prt 0 varval])
    Obs.Abs.SizeDclDef obsident -> prPrec i 0 (concatD [prt 0 obsident])

instance Print Obs.Abs.Obs where
  prt i = \case
    Obs.Abs.ObsName prefix threadid obsident -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "NAME"), prt 0 obsident])
    Obs.Abs.ObsLog prefix threadid lmsg -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "LOG"), prt 0 lmsg])
    Obs.Abs.ObsInit prefix threadid -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "INIT")])
    Obs.Abs.ObsTask prefix threadid taskname -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "TASK"), prt 0 taskname])
    Obs.Abs.ObsSignal prefix threadid n -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "SIGNAL"), prt 0 n])
    Obs.Abs.ObsDef prefix threadid varname varval -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "DEF"), prt 0 varname, prt 0 varval])
    Obs.Abs.ObsDecl prefix threadid typename varname -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "DECL"), prt 0 typename, prt 0 varname])
    Obs.Abs.ObsDeclVal prefix threadid typename varname varval -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "DECL"), prt 0 typename, prt 0 varname, prt 0 varval])
    Obs.Abs.ObsDeclArr prefix threadid typename varname sizedcl -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "DCLARRAY"), prt 0 typename, prt 0 varname, prt 0 sizedcl])
    Obs.Abs.ObsCall prefix threadid obsident args -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "CALL"), prt 0 obsident, prt 0 args])
    Obs.Abs.ObsState prefix threadid n state -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "STATE"), prt 0 n, prt 0 state])
    Obs.Abs.ObsStruct prefix threadid varname -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "STRUCT"), prt 0 varname])
    Obs.Abs.ObsSeq prefix threadid varname scalar -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "SEQ"), prt 0 varname, prt 0 scalar])
    Obs.Abs.ObsPtr prefix threadid varname varval -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "PTR"), prt 0 varname, prt 0 varval])
    Obs.Abs.ObsScalar prefix threadid varname varval -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "SCALAR"), prt 0 varname, prt 0 varval])
    Obs.Abs.ObsScalarIndex prefix threadid varname varindex varval -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "SCALAR"), prt 0 varname, prt 0 varindex, prt 0 varval])
    Obs.Abs.ObsEnd prefix threadid varname -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "END"), prt 0 varname])

instance Print Obs.Abs.Scalar where
  prt i = \case
    Obs.Abs.ObsScalarNone end -> prPrec i 0 (concatD [prt 0 end])
    Obs.Abs.ObsScalarCons prefix threadid varval scalar -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "SCALAR"), doc (showString "_"), prt 0 varval, prt 0 scalar])

instance Print Obs.Abs.End where
  prt i = \case
    Obs.Abs.ObsEndSeq prefix threadid varname -> prPrec i 0 (concatD [prt 0 prefix, prt 0 threadid, doc (showString "END"), prt 0 varname])

instance Print Obs.Abs.Prefix where
  prt i = \case
    Obs.Abs.Prefix -> prPrec i 0 (concatD [doc (showString "@@@")])
