-- File generated by the BNF Converter (bnfc 2.9.4).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Obs.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Obs.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transObsIdent :: Obs.Abs.ObsIdent -> Result
transObsIdent x = case x of
  Obs.Abs.ObsIdent string -> failure x

transObsStr :: Obs.Abs.ObsStr -> Result
transObsStr x = case x of
  Obs.Abs.ObsStr string -> failure x

transObsList :: Obs.Abs.ObsList -> Result
transObsList x = case x of
  Obs.Abs.ObsListCons obs obslist -> failure x
  Obs.Abs.ObsListOne obs -> failure x

transObs :: Obs.Abs.Obs -> Result
transObs x = case x of
  Obs.Abs.ObsName threadid obsident -> failure x
  Obs.Abs.ObsLog threadid lmsg -> failure x
  Obs.Abs.ObsInit threadid -> failure x
  Obs.Abs.ObsTask threadid taskname -> failure x
  Obs.Abs.ObsSignal threadid integer -> failure x
  Obs.Abs.ObsDef threadid varname varval -> failure x
  Obs.Abs.ObsDecl threadid typename varname -> failure x
  Obs.Abs.ObsDeclVal threadid typename varname varval -> failure x
  Obs.Abs.ObsDeclArr threadid typename varname sizedcl -> failure x
  Obs.Abs.ObsCall threadid obsident args -> failure x
  Obs.Abs.ObsState threadid integer state -> failure x
  Obs.Abs.ObsStruct threadid varname -> failure x
  Obs.Abs.ObsSeq threadid varname scalar -> failure x
  Obs.Abs.ObsPtr threadid varname varval -> failure x
  Obs.Abs.ObsScalar threadid varname varval -> failure x
  Obs.Abs.ObsScalarIndex threadid varname varindex varval -> failure x
  Obs.Abs.ObsEnd threadid varname -> failure x

transScalar :: Obs.Abs.Scalar -> Result
transScalar x = case x of
  Obs.Abs.ObsScalarNone end -> failure x
  Obs.Abs.ObsScalarCons threadid varval scalar -> failure x

transEnd :: Obs.Abs.End -> Result
transEnd x = case x of
  Obs.Abs.ObsEndSeq threadid varname -> failure x

transArgs :: Obs.Abs.Args -> Result
transArgs x = case x of
  Obs.Abs.ArgsConsString obsstr args -> failure x
  Obs.Abs.ArgsConsInteger integer args -> failure x
  Obs.Abs.ArgsConsDouble double args -> failure x
  Obs.Abs.ArgsOne -> failure x

transLMsg :: Obs.Abs.LMsg -> Result
transLMsg x = case x of
  Obs.Abs.LmsgConsString obsstr lmsg -> failure x
  Obs.Abs.LmsgOne -> failure x

transTaskname :: Obs.Abs.Taskname -> Result
transTaskname x = case x of
  Obs.Abs.TaskName obsident -> failure x

transVarname :: Obs.Abs.Varname -> Result
transVarname x = case x of
  Obs.Abs.VarName obsident -> failure x

transVarval :: Obs.Abs.Varval -> Result
transVarval x = case x of
  Obs.Abs.VarValInt integer -> failure x
  Obs.Abs.VarValDouble double -> failure x
  Obs.Abs.VarValNull -> failure x
  Obs.Abs.VarValStr obsstr -> failure x

transTypename :: Obs.Abs.Typename -> Result
transTypename x = case x of
  Obs.Abs.TypeName obsident -> failure x

transState :: Obs.Abs.State -> Result
transState x = case x of
  Obs.Abs.State obsident -> failure x

transVarindex :: Obs.Abs.Varindex -> Result
transVarindex x = case x of
  Obs.Abs.VarIndex integer -> failure x

transThreadId :: Obs.Abs.ThreadId -> Result
transThreadId x = case x of
  Obs.Abs.ThreadId integer -> failure x

transSizeDcl :: Obs.Abs.SizeDcl -> Result
transSizeDcl x = case x of
  Obs.Abs.SizeDclVar varval -> failure x
  Obs.Abs.SizeDclDef obsident -> failure x
