-- File generated by the BNF Converter (bnfc 2.9.4).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Obs.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Obs.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transObsString :: Obs.Abs.ObsString -> Result
transObsString x = case x of
  Obs.Abs.ObsString string -> failure x

transName :: Obs.Abs.Name -> Result
transName x = case x of
  Obs.Abs.Mname obsstring -> failure x

transArgs :: Obs.Abs.Args -> Result
transArgs x = case x of
  Obs.Abs.ArgsOne obsstring -> failure x
  Obs.Abs.ArgsCons obsstring args -> failure x

transLMsg :: Obs.Abs.LMsg -> Result
transLMsg x = case x of
  Obs.Abs.LmsgOne obsstring -> failure x
  Obs.Abs.LmsgCons obsstring lmsg -> failure x

transTaskname :: Obs.Abs.Taskname -> Result
transTaskname x = case x of
  Obs.Abs.TaskName obsstring -> failure x

transVarname :: Obs.Abs.Varname -> Result
transVarname x = case x of
  Obs.Abs.VarName obsstring -> failure x

transVarval :: Obs.Abs.Varval -> Result
transVarval x = case x of
  Obs.Abs.VarVal obsstring -> failure x

transTypename :: Obs.Abs.Typename -> Result
transTypename x = case x of
  Obs.Abs.TypeName obsstring -> failure x

transState :: Obs.Abs.State -> Result
transState x = case x of
  Obs.Abs.State obsstring -> failure x

transVarindex :: Obs.Abs.Varindex -> Result
transVarindex x = case x of
  Obs.Abs.VarIndex integer -> failure x

transObs :: Obs.Abs.Obs -> Result
transObs x = case x of
  Obs.Abs.ObsName integer name -> failure x
  Obs.Abs.ObsLog integer lmsg -> failure x
  Obs.Abs.ObsInit integer -> failure x
  Obs.Abs.ObsTask integer taskname -> failure x
  Obs.Abs.ObsSignal integer1 integer2 -> failure x
  Obs.Abs.ObsDef integer varname varval -> failure x
  Obs.Abs.ObsDeclVal integer typename varname varval -> failure x
  Obs.Abs.ObsDecl integer typename varname -> failure x
  Obs.Abs.ObsDeclArr integer typename varname varval -> failure x
  Obs.Abs.ObsCall integer args -> failure x
  Obs.Abs.ObsState integer1 integer2 state -> failure x
  Obs.Abs.ObsStruct integer varname -> failure x
  Obs.Abs.ObsSeq integer varname scalar -> failure x
  Obs.Abs.ObsPtr integer varname varval -> failure x
  Obs.Abs.ObsScalar integer varname varval -> failure x
  Obs.Abs.ObsScalarIndex integer varname varindex varval -> failure x
  Obs.Abs.ObsEnd integer varname -> failure x

transScalar :: Obs.Abs.Scalar -> Result
transScalar x = case x of
  Obs.Abs.ObsScalarCons integer varval scalar -> failure x
  Obs.Abs.ObsScalarNone end -> failure x

transEnd :: Obs.Abs.End -> Result
transEnd x = case x of
  Obs.Abs.ObsEndSeq integer varname -> failure x
