-- File generated by the BNF Converter (bnfc 2.9.4).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Erl.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Erl.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transStmt :: Erl.Abs.Stmt -> Result
transStmt x = case x of
  Erl.Abs.Stmt expr -> failure x

transExpr :: Erl.Abs.Expr -> Result
transExpr x = case x of
  Erl.Abs.SExprOne -> failure x
  Erl.Abs.SExprNone -> failure x
